import fs from "fs";
import path from "path";

const GLOBAL_I18N_VARS = {
  appName: "Shared Plates",
};
export const SUPPORTED_LANGUAGES = ["en", "cn"];

function hasPlaceholders(str) {
  return /{{(.*?)}}/.test(str);
}

// Load English first (base)
const enFile = path.resolve("./src/i18n/en.json");
const enJson = JSON.parse(fs.readFileSync(enFile, "utf-8")).translation;

// Helper to merge missing keys
function backfill(base, target) {
  const merged = { ...base };
  for (const key in base) {
    if (key in target && typeof target[key] === "string") {
      merged[key] = target[key];
    }
  }
  return merged;
}

// Start generating TS file
let out = `/* AUTO-GENERATED by generate-i18n.ts */\n`;
out += `export const GLOBAL_I18N_VARS = ${JSON.stringify(GLOBAL_I18N_VARS)};\n\n`;

for (const locale of SUPPORTED_LANGUAGES) {
  const file = path.resolve(`./src/i18n/${locale}.json`);
  let json = {};

  if (fs.existsSync(file)) {
    json = JSON.parse(fs.readFileSync(file, "utf-8")).translation;
  }

  // Backfill missing keys with English
  const translation = backfill(enJson, json);

  out += `export const ${locale} = {\n`;

  for (const key in translation) {
    const value = translation[key];

    if (hasPlaceholders(value)) {
      // dynamic → function
      out += `  ${key}: (vars: Record<string, string | number> = {}) => \`${value.replace(
        /{{(.*?)}}/g,
        "${vars.$1}",
      )}\`,\n`;
    } else {
      // static → string
      out += `  ${key}: \`${value}\`,\n`;
    }
  }

  out += `} as const;\n\n`;
}

// Output file
const outPath = path.resolve("./generated/generated-i18n.ts");
fs.writeFileSync(outPath, out);
console.log(`✅ i18n file generated at build time: ${outPath}`);
